# Generated by Django 4.2.7 on 2025-12-15 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.CharField(default='default-avatar.png', max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('elo_rating', models.IntegerField(default=1200)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('achievement_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('tournament', 'Tournament'), ('match', 'Match'), ('special', 'Special'), ('social', 'Social'), ('milestone', 'Milestone')], default='tournament', max_length=20)),
                ('requirement_type', models.CharField(choices=[('wins', 'Wins'), ('tournaments_played', 'Tournaments Played'), ('elo_reached', 'ELO Reached'), ('streak', 'Streak'), ('special', 'Special')], max_length=30)),
                ('requirement_value', models.IntegerField(blank=True, null=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('match_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('forfeited', 'Forfeited')], default='scheduled', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('white_win', 'White Win'), ('black_win', 'Black Win'), ('draw', 'Draw'), ('forfeit', 'Forfeit')], max_length=20, null=True)),
                ('white_elo_before', models.IntegerField(blank=True, null=True)),
                ('black_elo_before', models.IntegerField(blank=True, null=True)),
                ('white_elo_after', models.IntegerField(blank=True, null=True)),
                ('black_elo_after', models.IntegerField(blank=True, null=True)),
                ('elo_change', models.IntegerField(blank=True, null=True)),
                ('number_of_moves', models.IntegerField(blank=True, null=True)),
                ('time_control', models.CharField(blank=True, max_length=50, null=True)),
                ('pgn_notation', models.TextField(blank=True, null=True)),
                ('round_number', models.IntegerField(default=1)),
                ('match_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('black_player', models.ForeignKey(db_column='black_player_id', on_delete=django.db.models.deletion.CASCADE, related_name='black_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='TournamentActive',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_code', models.CharField(help_text='6-digit join code', max_length=6, unique=True)),
                ('tournament_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=16)),
                ('current_participants', models.IntegerField(default=0)),
                ('tournament_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tournament_type', models.CharField(choices=[('elimination', 'Elimination'), ('round_robin', 'Round Robin')], default='elimination', max_length=30)),
                ('time_control', models.CharField(blank=True, max_length=50, null=True)),
                ('min_elo', models.IntegerField(default=0)),
                ('max_elo', models.IntegerField(default=3000)),
                ('code_expires_at', models.DateTimeField(blank=True, help_text='Code invalid after tournament ends', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments_active',
            },
        ),
        migrations.CreateModel(
            name='TournamentSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('organizer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('special_rules', models.TextField(blank=True, null=True)),
                ('skill_level', models.CharField(choices=[('all', 'All'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='all', max_length=20)),
                ('time_format', models.CharField(choices=[('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical')], max_length=20)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('auto_pairing', models.BooleanField(default=True)),
                ('allow_byes', models.BooleanField(default=True)),
                ('max_rounds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'tournament_settings',
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('round_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'tournament_rounds',
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_rating_at_registration', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('withdrawal_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'tournament_registration',
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seed_number', models.IntegerField(blank=True, null=True)),
                ('current_round', models.IntegerField(default=1)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'tournament_participants',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_elo', models.IntegerField()),
                ('required_wins', models.IntegerField(default=0)),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titles',
                'indexes': [models.Index(fields=['title_name'], name='idx_title_name')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_create_tournament', models.BooleanField(default=False)),
                ('can_manage_tournament', models.BooleanField(default=False)),
                ('can_delete_tournament', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_all_matches', models.BooleanField(default=True)),
                ('can_edit_match_results', models.BooleanField(default=False)),
                ('can_award_titles', models.BooleanField(default=False)),
                ('can_access_admin_panel', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'roles',
                'indexes': [models.Index(fields=['role_name'], name='idx_role_name')],
            },
        ),
        migrations.CreateModel(
            name='PrizeDistribution',
            fields=[
                ('prize_id', models.AutoField(primary_key=True, serialize=False)),
                ('placement', models.IntegerField()),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prize_type', models.CharField(choices=[('cash', 'Cash'), ('trophy', 'Trophy'), ('certificate', 'Certificate'), ('medal', 'Medal'), ('other', 'Other')], default='cash', max_length=20)),
                ('prize_description', models.TextField(blank=True, null=True)),
                ('awarded_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('awarded_to_player', models.ForeignKey(blank=True, db_column='awarded_to_player_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(db_column='tournament_id', on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'prize_distribution',
            },
        ),
        migrations.CreateModel(
            name='PlayerTitle',
            fields=[
                ('player_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('awarded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('auto_unlocked', models.BooleanField(default=True)),
                ('awarded_by', models.ForeignKey(blank=True, db_column='awarded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles_awarded', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, to='chess.title')),
            ],
            options={
                'db_table': 'player_titles',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsHistory',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('recorded_date', models.DateField()),
                ('elo_rating', models.IntegerField()),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('highest_elo', models.IntegerField(default=0)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_stats_history',
            },
        ),
        migrations.CreateModel(
            name='PlayerPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='Croatia', max_length=100)),
                ('preferred_time_format', models.CharField(choices=[('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical')], default='rapid', max_length=20)),
                ('theme', models.CharField(default='dark', max_length=50)),
                ('board_style', models.CharField(default='classic', max_length=50)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_tournament_start', models.BooleanField(default=True)),
                ('notification_match_result', models.BooleanField(default=True)),
                ('notification_title_awarded', models.BooleanField(default=True)),
                ('notification_registration', models.BooleanField(default=True)),
                ('language', models.CharField(default='hr', max_length=10)),
                ('timezone', models.CharField(default='Europe/Zagreb', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_preferences',
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('player_achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('unlocked_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.IntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(db_column='achievement_id', on_delete=django.db.models.deletion.CASCADE, to='chess.achievement')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_achievements',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('registration', 'Registration'), ('tournament_start', 'Tournament Start'), ('match_result', 'Match Result'), ('title_awarded', 'Title Awarded'), ('pairing_update', 'Pairing Update'), ('system', 'System'), ('admin', 'Admin')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_match', models.ForeignKey(blank=True, db_column='related_match_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chess.match')),
                ('related_tournament', models.ForeignKey(blank=True, db_column='related_tournament_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='MatchPairing',
            fields=[
                ('pairing_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_number', models.IntegerField()),
                ('result', models.CharField(choices=[('white_win', 'White Win'), ('black_win', 'Black Win'), ('draw', 'Draw'), ('forfeit', 'Forfeit'), ('bye', 'Bye'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('is_bye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('black_player', models.ForeignKey(blank=True, db_column='black_player_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_pairings', to=settings.AUTH_USER_MODEL)),
                ('bye_player', models.ForeignKey(blank=True, db_column='bye_player_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bye_pairings', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, db_column='match_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess.match')),
                ('round', models.ForeignKey(db_column='round_id', on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentround')),
                ('white_player', models.ForeignKey(blank=True, db_column='white_player_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_pairings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_pairings',
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('player_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=10)),
                ('elo_change', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, to='chess.match')),
                ('opponent', models.ForeignKey(db_column='opponent_id', on_delete=django.db.models.deletion.CASCADE, related_name='opponent_history', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, db_column='tournament_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'match_history',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, db_column='tournament_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess.tournamentactive'),
        ),
        migrations.AddField(
            model_name='match',
            name='white_player',
            field=models.ForeignKey(db_column='white_player_id', on_delete=django.db.models.deletion.CASCADE, related_name='white_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, db_column='winner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('award_title', 'Award Title'), ('revoke_title', 'Revoke Title'), ('edit_tournament', 'Edit Tournament'), ('delete_tournament', 'Delete Tournament'), ('ban_player', 'Ban Player'), ('unban_player', 'Unban Player'), ('edit_match', 'Edit Match'), ('delete_match', 'Delete Match'), ('system_config', 'System Config'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_match', models.ForeignKey(blank=True, db_column='target_match_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess.match')),
                ('target_player', models.ForeignKey(blank=True, db_column='target_player_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_tournament', models.ForeignKey(blank=True, db_column='target_tournament_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess.tournamentactive')),
            ],
            options={
                'db_table': 'admin_logs',
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category'], name='idx_category'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['achievement_name'], name='idx_achievement_name'),
        ),
        migrations.AddField(
            model_name='player',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.RESTRICT, to='chess.role'),
        ),
        migrations.AddField(
            model_name='player',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='tournamentsetting',
            index=models.Index(fields=['tournament'], name='idx_tournament_ts'),
        ),
        migrations.AddIndex(
            model_name='tournamentsetting',
            index=models.Index(fields=['skill_level'], name='idx_skill_level'),
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['tournament'], name='idx_tournament_tround'),
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['round_number'], name='idx_round_number'),
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['round_status'], name='idx_status_tround'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentround',
            unique_together={('tournament', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['tournament'], name='idx_tournament_tr'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['player'], name='idx_player_tr'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['status'], name='idx_status_tr'),
        ),
        migrations.AddIndex(
            model_name='tournamentregistration',
            index=models.Index(fields=['payment_status'], name='idx_payment_status'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('tournament', 'player')},
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament'], name='idx_tournament_tp'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['player'], name='idx_player_tp'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'player')},
        ),
        migrations.AddIndex(
            model_name='tournamentactive',
            index=models.Index(fields=['tournament_status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='tournamentactive',
            index=models.Index(fields=['start_date'], name='idx_start_date'),
        ),
        migrations.AddIndex(
            model_name='tournamentactive',
            index=models.Index(fields=['tournament_code'], name='idx_tournament_code'),
        ),
        migrations.AddIndex(
            model_name='prizedistribution',
            index=models.Index(fields=['tournament'], name='idx_tournament_pd'),
        ),
        migrations.AddIndex(
            model_name='prizedistribution',
            index=models.Index(fields=['placement'], name='idx_placement'),
        ),
        migrations.AddIndex(
            model_name='playertitle',
            index=models.Index(fields=['player'], name='idx_player_pt'),
        ),
        migrations.AddIndex(
            model_name='playertitle',
            index=models.Index(fields=['is_unlocked'], name='idx_unlocked'),
        ),
        migrations.AlterUniqueTogether(
            name='playertitle',
            unique_together={('player', 'title')},
        ),
        migrations.AddIndex(
            model_name='playerstatshistory',
            index=models.Index(fields=['player'], name='idx_player_psh'),
        ),
        migrations.AddIndex(
            model_name='playerstatshistory',
            index=models.Index(fields=['recorded_date'], name='idx_date'),
        ),
        migrations.AddIndex(
            model_name='playerstatshistory',
            index=models.Index(fields=['elo_rating'], name='idx_elo_psh'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstatshistory',
            unique_together={('player', 'recorded_date')},
        ),
        migrations.AddIndex(
            model_name='playerpreference',
            index=models.Index(fields=['player'], name='idx_player_pp'),
        ),
        migrations.AddIndex(
            model_name='playerachievement',
            index=models.Index(fields=['player'], name='idx_player_pa'),
        ),
        migrations.AddIndex(
            model_name='playerachievement',
            index=models.Index(fields=['is_unlocked'], name='idx_unlocked_pa'),
        ),
        migrations.AlterUniqueTogether(
            name='playerachievement',
            unique_together={('player', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['player'], name='idx_player_n'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='idx_is_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='idx_type'),
        ),
        migrations.AddIndex(
            model_name='matchpairing',
            index=models.Index(fields=['round'], name='idx_round'),
        ),
        migrations.AddIndex(
            model_name='matchpairing',
            index=models.Index(fields=['board_number'], name='idx_board_number'),
        ),
        migrations.AddIndex(
            model_name='matchpairing',
            index=models.Index(fields=['match'], name='idx_match_mp'),
        ),
        migrations.AddIndex(
            model_name='matchhistory',
            index=models.Index(fields=['player'], name='idx_player_mh'),
        ),
        migrations.AddIndex(
            model_name='matchhistory',
            index=models.Index(fields=['match_date'], name='idx_match_date_mh'),
        ),
        migrations.AddIndex(
            model_name='matchhistory',
            index=models.Index(fields=['result'], name='idx_result'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament'], name='idx_tournament_m'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['white_player'], name='idx_white_player'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['black_player'], name='idx_black_player'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_date'], name='idx_match_date'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_status'], name='idx_status_m'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin'], name='idx_admin'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['action_type'], name='idx_action_type'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['created_at'], name='idx_created_at_al'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['username'], name='idx_username'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['email'], name='idx_email'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['elo_rating'], name='idx_elo'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['role'], name='idx_role'),
        ),
    ]
