# Generated by Django 4.2.7 on 2026-01-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='google_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
