# Generated by Django 4.2.7 on 2026-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_player_google_id_player_google_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chesscom_avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chesscom_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chesscom_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
