# Generated by Django 4.2.7 on 2026-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_add_chesscom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo_blitz',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_bullet',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_daily',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_puzzle',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_rapid',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='tournamentactive',
            name='pairing_system',
            field=models.CharField(choices=[('random', 'Random'), ('manual', 'Manual'), ('rating', 'By Rating'), ('swiss', 'Swiss System')], default='random', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentactive',
            name='pairings_confirmed',
            field=models.BooleanField(default=False, help_text='True if organizer confirmed manual pairings'),
        ),
        migrations.AddField(
            model_name='tournamentactive',
            name='time_control_minutes',
            field=models.IntegerField(default=5, help_text='Base time in minutes'),
        ),
        migrations.AddField(
            model_name='tournamentactive',
            name='time_control_type',
            field=models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('daily', 'Daily')], default='blitz', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentactive',
            name='time_increment_seconds',
            field=models.IntegerField(default=0, help_text='Increment per move in seconds'),
        ),
        migrations.AlterField(
            model_name='tournamentactive',
            name='tournament_type',
            field=models.CharField(choices=[('elimination', 'Elimination'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss System')], default='elimination', max_length=30),
        ),
    ]
