# Generated by Django 4.2.7 on 2026-01-11 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_add_elo_types_and_tournament_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('white_win', 'White Wins'), ('black_win', 'Black Wins'), ('draw', 'Draw'), ('stalemate', 'Stalemate'), ('timeout', 'Timeout'), ('resignation', 'Resignation'), (None, 'Not finished')], max_length=20, null=True)),
                ('pgn', models.TextField(blank=True, null=True)),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('move_history', models.TextField(blank=True, null=True)),
                ('current_turn', models.CharField(default='white', max_length=10)),
                ('move_count', models.IntegerField(default=0)),
                ('time_control_minutes', models.IntegerField(blank=True, null=True)),
                ('time_increment_seconds', models.IntegerField(default=0)),
                ('white_time_remaining', models.IntegerField(blank=True, null=True)),
                ('black_time_remaining', models.IntegerField(blank=True, null=True)),
                ('last_move_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('black_player', models.ForeignKey(db_column='black_player_id', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, db_column='match_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chess.match')),
                ('tournament', models.ForeignKey(blank=True, db_column='tournament_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chess.tournamentactive')),
                ('white_player', models.ForeignKey(db_column='white_player_id', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games',
                'indexes': [models.Index(fields=['tournament'], name='idx_game_tournament'), models.Index(fields=['white_player'], name='idx_game_white_player'), models.Index(fields=['black_player'], name='idx_game_black_player'), models.Index(fields=['status'], name='idx_game_status'), models.Index(fields=['created_at'], name='idx_game_created')],
            },
        ),
    ]
