# Generated by Django 4.2.7 on 2026-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentactive',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, tournament appears in public listings'),
        ),
    ]
