# Generated by Django 4.2.7 on 2026-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_tournamentactive_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Novi (400 ELO)'), ('intermediate', 'Poznajem igru (700 ELO)'), ('advanced', 'Iskusan (1000 ELO)')], default='intermediate', help_text='Initial experience level set during registration', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='is_provisional',
            field=models.BooleanField(default=True, help_text='True if player has played less than 5 matches'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(default=0, help_text='Number of rated matches played'),
        ),
    ]
