# Generated by Django 4.2.7 on 2026-01-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_player_experience_level_player_is_provisional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_title',
            field=models.ForeignKey(blank=True, db_column='active_title_id', help_text='Currently displayed title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_players', to='chess.title'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
