# Generated by Django 4.2.7 on 2026-01-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_add_profile_picture_and_active_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auth_token',
            field=models.CharField(blank=True, help_text='Authentication token for API requests', max_length=64, null=True, unique=True),
        ),
    ]
