# Generated by Django 4.2.7 on 2026-01-13 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0009_player_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'friendships',
            },
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('tournament_start', 'Tournament Start'), ('match_result', 'Match Result'), ('title_awarded', 'Title Awarded'), ('pairing_update', 'Pairing Update'), ('challenge', 'Challenge'), ('system', 'System'), ('admin', 'Admin')], db_column='type', default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Obavijest', max_length=100),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='idx_type'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_player',
            field=models.ForeignKey(db_column='from_player_id', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_player',
            field=models.ForeignKey(db_column='to_player_id', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['from_player'], name='idx_from_player'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['to_player'], name='idx_to_player'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status'], name='idx_friendship_status'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('from_player', 'to_player')},
        ),
    ]
