# Generated by Django 4.2.7 on 2026-01-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0010_add_friendship_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='white_joined',
            field=models.BooleanField(default=False),
        ),
    ]
