# Generated by Django 4.2.7 on 2026-01-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_add_player_join_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_offers_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='white_offers_draw',
            field=models.BooleanField(default=False),
        ),
    ]
