# Generated by Django 4.2.7 on 2026-01-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0012_add_draw_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture_source',
            field=models.CharField(choices=[('uploaded', 'Uploadana slika'), ('google', 'Google'), ('chesscom', 'Chess.com')], default='uploaded', help_text='Source of displayed profile picture', max_length=20),
        ),
    ]
