# Generated by Django 4.2.7 on 2026-01-29 19:36

import chess.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0013_add_profile_picture_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentactive',
            name='current_round',
            field=models.IntegerField(default=1, help_text='Current round number for tournament progression'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to=chess.models.profile_picture_path),
        ),
    ]
